services:
  artifactory:
    image: jfrog-artifatcory-pro-cracked:7.117.14
    environment:
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://postgresql:5432/artifactory
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=8082
      - JF_SHARED_DATABASE_TYPE=postgresql
      - JF_SHARED_DATABASE_USERNAME=jfrog-pg-admin
      - JF_SHARED_DATABASE_PASSWORD=<SECURE_PASSWORD>
    ports:
      - 8082:8082
      - 8081:8081
    volumes:
      - ./jfrog-data:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgresql
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  postgresql:
    image: postgres:16.6-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=jfrog-pg-admin
      - POSTGRES_PASSWORD=<SECURE_PASSWORD>
    ports:
      - 5432:5432
    volumes:
      - ./jfrog-postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
